# Generated by Django 5.1.2 on 2024-11-08 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herbicide_name', models.CharField(max_length=100, verbose_name="Nom de l'herbicide")),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût unitaire herbicide')),
                ('labor_cost_per_ha', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût de travail par ha')),
                ('file_fee_fcfa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frais de dossier en FCFA')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loan', models.PositiveIntegerField(default=0)),
                ('payable_loan', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to='loginApp.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='loanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status_date', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=1)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loanApp.loancategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_customer', to='loginApp.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='loanTransaction',
            fields=[
                ('transaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment', models.PositiveIntegerField(default=0)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_customer', to='loginApp.customersignup')),
            ],
        ),
    ]
