# Generated by Django 5.1.3 on 2024-11-10 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loan', models.PositiveIntegerField(default=0)),
                ('payable_loan', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to='loginApp.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='loanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status_date', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='En cours de traitement', max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=1)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_customer', to='loginApp.customersignup')),
            ],
        ),
        migrations.CreateModel(
            name='loanTransaction',
            fields=[
                ('transaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment', models.PositiveIntegerField(default=0)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_customer', to='loginApp.customersignup')),
            ],
        ),
    ]
