# Generated by Django 5.1.2 on 2024-11-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0002_alter_loanrequest_category_delete_loancategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(default='En cours de traitement', max_length=100),
        ),
    ]
